export const STATUS_GAME_START = "STATUS_GAME_START";
export const STATUS_GAME_STOP = "STATUS_GAME_STOP";
export const STATUS_BUTTON_START_ON = "STATUS_BUTTON_START_ON";
export const STATUS_BUTTON_START_OFF = "STATUS_BUTTON_START_OFF";
export const STATUS_BUTTON_STOP_ON = "STATUS_BUTTON_STOP_ON";
export const STATUS_BUTTON_STOP_OFF = "STATUS_BUTTON_STOP_OFF";
