export const STATUS_GAME_START = "STATUS_GAME_START";
export const STATUS_GAME_STOP = "STATUS_GAME_STOP";
export const STATUS_BUTTON_START = "STATUS_BUTTON_START";
export const STATUS_BUTTON_STOP = "STATUS_BUTTON_STOP";
